app = "solr-marlon"      # use exatamente este nome ao criar o app
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "solrdata"
  destination = "/var/solr"

[http_service]
  internal_port = 8983
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1


