app = "solr-marlon"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "solrdata"
  destination = "/var/solr"

[http_service]
  internal_port = 8983
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

  # Health-check explícito no endpoint do Solr
  [http_service.checks]
    [http_service.checks.http]
      # usa a mesma porta do serviço
      interval = "10s"
      timeout = "5s"
      method = "GET"
      path = "/solr/admin/info/system?wt=json"

  


