app = "solr-marlon"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "solrdata"
  destination = "/var/solr"

[http_service]
  internal_port = 8983
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

  [[http_service.checks]]
    method = "get"
    path = "/solr/admin/info/system?wt=json"
    interval = "10s"
    timeout  = "5s"
    grace_period = "30s"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = 1024   # <<< use 1024 MB (recomendado). 512 MB é o mínimo que costuma iniciar.



  


